=== cvakarna/coding_practice/Parser/Xml/employee-xsd/src/main/resources/employee.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

	<xs:element name="Company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:integer" name="emp-id" maxOccurs="1"
								minOccurs="1" />
							<xs:element type="xs:string" name="FirstName"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:string" name="LastName"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:integer" name="Mobile_number"
								maxOccurs="1" minOccurs="1" />
						</xs:sequence>
						<xs:attribute type="xs:short" name="id" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="Employee_Parents" maxOccurs="1"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="FatherName"
								maxOccurs="1" minOccurs="1" />
							<xs:element type="xs:string" name="MotherName"
								maxOccurs="1" minOccurs="1" />
						</xs:sequence>
						<xs:attribute type="xs:short" name="id" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

	</xs:element>
</xs:schema>

=== cvakarna/coding_practice/Parser/Xml/employee-xsd/src/main/resources/employee.xml
<?xml version="1.0" encoding="UTF-8"?>

<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="employee.xsd" 	>
	<Employee id="100">
		<emp-id>101</emp-id>
		<FirstName>JothiPandiyan</FirstName>
		<LastName>M</LastName>		
		<Mobile_number>8015340590</Mobile_number>
	</Employee>
	<Employee_Parents id="100" >
		<FatherName>Mani</FatherName>
		<MotherName>Bayammal</MotherName>
	</Employee_Parents>
</Company>
